### ISSUE TITLE
python/pie: gdb.Inferior.attach coring

### ISSUE THREAD

**Issue by pmqs** [tromey/gdb#38]
After build the python/pie branch I got a core in **_PyArg_ParseTupleAndKeywords_SizeT** when I ran this

```
import gdb
gdb.Inferior().attach(14876)
```

I got past the core by changing the "attach" entry in **inferior_object_methods** to include **METH_KEYWORDS**. 

```
  { "attach", (PyCFunction) infpy_attach, METH_VARARGS | METH_KEYWORDS,
    "attach (PID) -> None.\n\
Attach to the specified process." },
```

Rerunning the test gave me this, which is much better than a core. Will dig some more.

```
Traceback (most recent call last):
  File "try1.py", line 2, in <module>
    gdb.Inferior().attach(14876)
gdb.error: cannot attach an already executing inferior
```

cheers
Paul

**Comment by pmqs** [comment]
Dug some more

Looks like any form of attach is broken with the python/pie branch. I get a core when I tried this from the gdb command prompt

```
(gdb) attach 22359
Attaching to process 22359
Segmentation fault (core dumped)
```

Looking at the gdb core it's blowing up in  **linux_nat_thread_address_space**

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  linux_nat_thread_address_space (t=<optimized out>, ptid=...)
    at linux-nat.c:4791
4791          pid = ptid_get_pid (lwp->ptid);

(gdb) p ptid
$1 = {pid = 22359, lwp = 0, tid = 0}

(gdb) p lwp
$2 = (struct lwp_info *) 0x0
```

Not sure where to go next to root cause this.

Here is the stack trace.

```
(gdb) bt
#0  linux_nat_thread_address_space (t=<optimized out>, ptid=...)
    at linux-nat.c:4791
#1  0x00007ff5d5871757 in target_thread_address_space (ptid=...)
    at target.c:3269
#2  0x00007ff5d57e75d3 in get_thread_arch_regcache (ptid=..., 
    gdbarch=0x7ff5d625a8d0) at regcache.c:489
#3  0x00007ff5d57e76d9 in get_current_regcache () at regcache.c:512
#4  0x00007ff5d591d795 in get_current_frame () at frame.c:1420
#5  0x00007ff5d591e515 in get_selected_frame (message=<optimized out>)
    at frame.c:1476
#6  0x00007ff5d5860597 in get_current_arch () at arch-utils.c:758
#7  0x00007ff5d5797f7d in add_thread_object (tp=0x7ff5d6261420)
    at ./python/py-inferior.c:249
#8  0x00007ff5d5882f25 in generic_observer_notify (subject=<optimized out>, 
    args=0x7fff5c977000) at observer.c:167
#9  0x00007ff5d5883889 in observer_notify_new_thread (t=<optimized out>)
    at observer.inc:407
#10 0x00007ff5d584833b in add_thread_silent (ptid=...) at thread.c:241
#11 0x00007ff5d57299ef in inf_ptrace_attach (ops=<optimized out>, 
    args=<optimized out>, from_tty=<optimized out>) at inf-ptrace.c:241
#12 0x00007ff5d5732092 in linux_nat_attach (ops=0x7ff5d6153340, 
    args=0x7ff5d6111187 "22359", from_tty=1) at linux-nat.c:1343
#13 0x00007ff5d5870d08 in target_attach (args=0x7ff5d6111187 "22359", 
---Type <return> to continue, or q <return> to quit---
    from_tty=1) at target.c:3794
#14 0x00007ff5d5830deb in attach (args=0x7ff5d6111187 "22359", from_tty=1, 
    async_exec=0) at infcmd.c:2554
#15 0x00007ff5d583103e in attach_command (args=0x7ff5d6111187 "22359", 
    from_tty=1) at infcmd.c:2633
#16 0x00007ff5d59153ff in execute_command (p=<optimized out>, from_tty=1)
    at top.c:468
#17 0x00007ff5d585266c in command_handler (command=0x7ff5d6111180 "")
    at event-top.c:435
#18 0x00007ff5d5853320 in command_line_handler (rl=<optimized out>)
    at event-top.c:632
#19 0x00007ff5d595e882 in rl_callback_read_char () at callback.c:220
#20 0x00007ff5d58526e9 in rl_callback_read_char_wrapper (
    client_data=<optimized out>) at event-top.c:164
#21 0x00007ff5d58516a4 in process_event () at event-loop.c:342
#22 0x00007ff5d5852247 in gdb_do_one_event () at event-loop.c:406
#23 0x00007ff5d58522a7 in start_event_loop () at event-loop.c:431
#24 0x00007ff5d584ae26 in captured_command_loop (data=<optimized out>)
    at main.c:267
#25 0x00007ff5d5848fab in catch_errors (
    func=0x7ff5d584ae10 <captured_command_loop>, func_args=0x0, 
    errstring=0x7ff5d5a1fff7 "", mask=RETURN_MASK_ALL) at exceptions.c:524
#26 0x00007ff5d584b5da in captured_main (data=0x7fff5c977620) at main.c:1070
---Type <return> to continue, or q <return> to quit---
#27 0x00007ff5d5848fab in catch_errors (func=0x7ff5d584af30 <captured_main>, 
    func_args=0x7fff5c977620, errstring=0x7ff5d5a1fff7 "", 
    mask=RETURN_MASK_ALL) at exceptions.c:524
#28 0x00007ff5d584ac3b in gdb_main (args=<optimized out>) at main.c:1079
#29 0x00007ff5d56f78f1 in main (argc=<optimized out>, argv=<optimized out>)
    at gdb.c:34

```

**Comment by tromey** [comment]
Sorry about the delay here.  I don't know offhand what's wrong here, all I can suggest is debugging :(

**Comment by pmqs** [comment]
Thanks Tom. If I do get anywhere I'll feed back the change.
